version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  chromatic:
    steps:
      - checkout
      - run: yarn chromatic --project-token=84svyadsh4w

workflows:
  version: 2
  build-and-chromatic-deploy:
    jobs:
      - build
      - chromatic:
          requires:
            - build
#          filters:
#            branches:
#              only: main